application: heyes-hrd
version: 10
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.html)
  static_files: \1
  upload: (.*\.html)

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /ico
  static_dir: ico
